apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prasanth-prod-ingress
  namespace: prasanth-prod
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "25m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - prasanthassociates.com
        - www.prasanthassociates.com
      secretName: prasanth-tls-cert
  rules:
    - host: prasanthassociates.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
    - host: www.prasanthassociates.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 3000
